{% set name = "iniconfig" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytest-dev/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8bbd2d27f7fc26cb01bf52bc99e7efd56a5a3f4e62c551aed2c9fb0cf4226153

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - hatch-vcs
    - hatchling>=1.26
  run:
    - python

test:
  source_files:
    - testing
  imports:
    - iniconfig
  commands:
    - pip check
    - pytest -vv testing
  requires:
    - pip
    - pytest

about:
  home: http://github.com/RonnyPfannschmidt/iniconfig
  summary: 'iniconfig: brain-dead simple config-ini parsing'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
