{% set name = "iniconfig" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytest-dev/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b485a7f6c060b2e758b6e58fd1bf7349a6f99954110ca61ceb59af25cf4ff458

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - setuptools-scm >=8
  run:
    - python

test:
  source_files:
    - testing
  imports:
    - iniconfig
  commands:
    - pip check
    - pytest -vv testing
  requires:
    - pip
    - pytest >=8.4.2

about:
  home: https://github.com/RonnyPfannschmidt/iniconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'iniconfig: brain-dead simple config-ini parsing'
  description: |
    iniconfig is a small and simple INI-file parser module having a unique set of features:
    o  maintains order of sections and entries
    o  supports multi-line values with or without line-continuations
    o  supports “#” comments everywhere
    o  raises errors with proper line-numbers
    o  no bells and whistles like automatic substitutions
    o  iniconfig raises an Error if two sections have the same name.
  dev_url: https://github.com/RonnyPfannschmidt/iniconfig
  doc_url: https://github.com/RonnyPfannschmidt/iniconfig

extra:
  recipe-maintainers:
    - nicoddemus
